blog/urls.py
from django.conf.urls import patterns, url


username_pattern = r'(?P<username>[a-zA-Z0-9_]+)'

urlpatterns = patterns(
    'blog.views',
    url(r'^$', 'index', name='index'),
    url('^' + username_pattern + r'/(?P<pk>\d+)/$', 'detail', name='post_detail'),  # noqa
    url(r'^new/$', 'new', name='post_new'),
    url(r'^(?P<pk>\d+)/edit/$', 'edit', name='post_edit'),
    url(r'^(?P<pk>\d+)/delete/$', 'delete', name='post_delete'),
    url(r'^(?P<pk>\d+)/like/$', 'post_like', name='post_like'),
    url(r'^(?P<pk>\d+)/unlike/$', 'post_unlike', name='post_unlike'),
    url(r'^(?P<post_id>\d+)/comments/new/$', 'comment_new', name='comment_new'),  # noqa
    url(r'^(?P<post_id>\d+)/comments/(?P<pk>\d+)/edit/$', 'comment_edit',
        name='comment_edit'),
    url(r'^(?P<post_id>\d+)/comments/(?P<pk>\d+)/delete/$',
        'comment_delete', name='comment_delete'),
    url('^' + username_pattern + '/$', 'author_home', name='author_home'),
    url('^' + username_pattern + '/follow/$', 'follow', name='author_follow'),  # noqa
    url('^' + username_pattern + '/unfollow/$', 'unfollow', name='author_unfollow'),  # noqa
)

shake/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='blog:index'), name='root'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', name='logout'),  # noqa
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', name='jsi18n'),
]

if settings.DEBUG and settings.MEDIA_URL.startswith('/'):
    media_url = settings.MEDIA_URL.strip('/')               # '/media/' -> 'media'  # noqa
    media_url_pattern = '^' + media_url + '/(?P<path>.*)$'  # '^media/(?P<path>.*)$'  # noqa
    urlpatterns += [
        url(media_url_pattern, 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

blog/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AnonymousUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ungettext
from blog.signals import app_ready
from blog.utils import random_name_upload_to


def on_app_ready(sender, **kwargs):
    def is_follow(self, to_user):
        if (self.id is not None) and (to_user.id is not None):
            return self.following_set.filter(to_user=to_user).exists()
        return False
    setattr(get_user_model(), 'is_follow', is_follow)

    def follow(self, to_user):
        if self.id is None:
            raise ValueError('Save {} model instance to DB first.'.format(self))  # noqa
        if not self.is_follow(to_user):
            self.following_set.create(to_user=to_user)
    setattr(get_user_model(), 'follow', follow)

    def unfollow(self, to_user):
        if self.id is None:
            raise ValueError('Save {} model instance to DB first.'.format(self))  # noqa
        self.following_set.filter(to_user=to_user).delete()
    setattr(get_user_model(), 'unfollow', unfollow)

    def following_summary(self):
        count = self.following_set.all().count()
        return ungettext('%(count)d post (single)', '%(count)d posts (plural)', count) % {  # noqa
            'count': count,
        }

    setattr(AnonymousUser, 'is_follow', lambda *args: False)
    setattr(AnonymousUser, 'follow', lambda *args: None)
    setattr(AnonymousUser, 'unfollow', lambda *args: None)

app_ready.connect(on_app_ready)


class UserFollow(models.Model):
    from_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='following_set')  # noqa
    to_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='follower_set')  # noqa
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = (
            ('from_user', 'to_user'),
        )


class Post(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_('author'))  # noqa
    title = models.CharField(max_length=100, verbose_name=_('title'))
    content = models.TextField(verbose_name=_('content'))
    attached_image = models.ImageField(
        upload_to=random_name_upload_to,
        blank=True,
        default='',
        verbose_name=_('attached_image')
    )
    lnglat = models.CharField(max_length=50, default='', verbose_name=_('lnglat'))  # noqa
    liked_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='liked_post_set')  # noqa
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-id',)
        verbose_name = _('post')
        verbose_name_plural = _('posts')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.author.username, self.id])  # noqa

    @property
    def lng(self):
        if self.lnglat:
            return self.lnglat.split(',')[0]

    @property
    def lat(self):
        if self.lnglat:
            return self.lnglat.split(',')[1]

    def is_liked(self, user):
        if user.id is None:
            return False
        return self.liked_users.filter(id=user.id).exists()

    def like(self, user):
        if user.id is not None:
            self.liked_users.add(user)

    def unlike(self, user):
        if user.id is not None:
            self.liked_users.remove(user)


class Comment(models.Model):
    post = models.ForeignKey(Post)
    message = models.TextField(verbose_name=_('message'))
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-id',)
        verbose_name = _('comment')
        verbose_name_plural = _('comments')

    def as_dict(self):
        return {
            'id': self.id,
            'message': self.message,
            'created_at': self.created_at,
            'updated_at': self.updated_at,
        }

blog/forms.py
from django import forms
from blog.models import Post, Comment
from blog.widgets import PointWidget
from blog.utils import square_image


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'attached_image', 'lnglat', )
        widgets = {
            'lnglat': PointWidget,
        }

    def __init__(self, *args, **kwargs):
        self.author = kwargs.pop('author', None)
        super(PostForm, self).__init__(*args, **kwargs)

    def clean_attached_image(self):
        attached_image = self.cleaned_data['attached_image']
        if attached_image:
            attached_image.file = square_image(attached_image.file, 400)
        return attached_image

    def save(self, commit=True):
        post = super(PostForm, self).save(commit=False)
        if self.author is not None:
            post.author = self.author
        if commit:
            post.save()
        return post


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('message', )
        widgets = {
            'message': forms.Textarea(attrs={'rows': 3}),
        }

blog/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import get_object_or_404, redirect
from django.views.generic import View, ListView, DetailView, CreateView, UpdateView, DeleteView   # noqa
from blog.models import Post, Comment
from blog.forms import PostForm, CommentForm
from blog.mixins import FormValidMessageMixin


index = ListView.as_view(
    model=get_user_model(),
    context_object_name='author_list',
    template_name='blog/author_list.html'
)


class PostDetailView(DetailView):
    model = Post

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['comment_form'] = CommentForm()
        context['author'] = self.object.author
        return context

detail = PostDetailView.as_view()


class PostCreateView(FormValidMessageMixin, CreateView):
    model = Post
    form_class = PostForm
    form_valid_message = 'Added a new post.'

    def get_form_kwargs(self):
        kwargs = super(PostCreateView, self).get_form_kwargs()
        kwargs['author'] = self.request.user
        return kwargs

new = login_required(PostCreateView.as_view())


class PostUpdateView(FormValidMessageMixin, UpdateView):
    model = Post
    form_class = PostForm
    form_valid_message = 'Edited a post.'

edit = login_required(PostUpdateView.as_view())


class PostDeleteView(FormValidMessageMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:index')
    form_valid_message = 'Deleted a post.'

delete = PostDeleteView.as_view()


class PostLikeView(View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        post.like(request.user)
        return redirect(request.META['HTTP_REFERER'])

post_like = login_required(PostLikeView.as_view())


class PostUnlikeView(View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, id=self.kwargs['pk'])
        post.unlike(request.user)
        return redirect(request.META['HTTP_REFERER'])

post_unlike = login_required(PostUnlikeView.as_view())


class CommentCreateView(FormValidMessageMixin, CreateView):
    form_class = CommentForm
    form_valid_message = 'Added a new comment.'

    def get_success_url(self):
        return reverse(self.object.post.get_absolute_url())

    def form_valid(self, form):
        post = get_object_or_404(Post, id=self.kwargs['post_id'])
        self.object = form.save(commit=False)
        self.object.post = post
        self.object.save()

        if self.request.is_ajax():
            return self.object

        return super(CommentCreateView, self).form_valid(form)

comment_new = CommentCreateView.as_view()


class CommentUpdateView(FormValidMessageMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    form_valid_message = 'Edited a new comment.'

    def get_success_url(self):
        return reverse(self.object.post.get_absolute_url())

comment_edit = CommentUpdateView.as_view()


class CommentDeleteView(FormValidMessageMixin, DeleteView):
    model = Comment
    form_valid_message = 'Deleted a comment.'

    def get_success_url(self):
        return reverse(self.object.post.get_absolute_url())

comment_delete = CommentDeleteView.as_view()


class AuthorHomeView(ListView):
    model = Post

    def get_queryset(self):
        self.author = get_object_or_404(get_user_model(), username=self.kwargs['username'])  # noqa
        qs = super(AuthorHomeView, self).get_queryset()
        return qs.filter(author=self.author)

    def get_context_data(self, **kwargs):
        context = super(AuthorHomeView, self).get_context_data(**kwargs)
        context['author'] = self.author
        return context

author_home = AuthorHomeView.as_view()


class AuthorFollowView(View):
    def get(self, request, *args, **kwargs):
        author = get_object_or_404(get_user_model(), username=kwargs['username'])  # noqa
        request.user.follow(author)
        messages.info(request, 'Followed.')
        return redirect('blog:author_home', kwargs['username'])

follow = login_required(AuthorFollowView.as_view())


class AuthorUnfollowView(View):
    def get(self, request, *args, **kwargs):
        author = get_object_or_404(get_user_model(), username=kwargs['username'])  # noqa
        request.user.unfollow(author)
        messages.info(request, 'Unfollowed.')
        return redirect('blog:author_home', kwargs['username'])

unfollow = login_required(AuthorUnfollowView.as_view())

blog/templates/blog/author_list.html
{% extends "layout.html" %}

{% block content %}

    <div class="row">
        <div class="col-sm-4">
            <span>Followers</span>
            <ul>
                {% for follow in user.follower_set.all %}
                    <li>
                        <a href="{% url "blog:author_home" follow.from_user.username %}">
                            {{ follow.from_user }}
                        </a>
                    </li>
                {% empty %}
                    <li>Empty</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-4">
            <span>Following</span>
            <p><small>{{ user.following_summary }}</small></p>
            <ul>
                {% for follow in user.following_set.all %}
                    <li>
                        <a href="{% url "blog:author_home" follow.to_user.username %}">
                            {{ follow.to_user }}
                        </a>
                    </li>
                {% empty %}
                    <li>Empty</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-sm-4">
            <span>All Bloggers</span>
            <ul>
                {% for user in author_list %}
                    <li>
                        <a href="{% url "blog:author_home" user.username %}">
                            {{ user }}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

blog/templates/blog/comment_form.html
{% include "blog/form.html" %}

blog/templates/blog/form.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="panel panel-default">
                    {% if form_legend %}
                        <div class="panel-heading">
                            {{ form_legend }}
                        </div>
                    {% endif %}
                    <div class="panel-body">
                        {% bootstrap_form form %}
                    </div>
                    <div class="panel-footer text-right">
                        <button type="submit" class="btn btn-primary">Post</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <hr/>
    <a href="{% url "blog:index" %}" class="btn btn-default">List</a>
{% endblock %}

blog/templates/blog/index.html
{% extends "layout.html" %}

{% block content %}
<table class="table table-hover table-bordered">
    {% for post in post_list %}
    <tr>
        <td>
            <a href="{% url "blog:post_detail" post.id %}">
                {{ post.title }}
            </a>
        </td>
        <td>{{ post.updated_at }}</td>
    </tr>
    {% endfor %}
</table>

<hr/>
<a href="{% url "blog:post_new" %}" class="btn btn-default">New Post</a>
{% endblock %}

blog/templates/blog/point_widget.html
<style>
    {# /* Google Map default style */ #}
    #map_canvas_{{ id }} img {
        max-width: none;
    }
    #map_canvas_{{ id }} label {
        width: auto;
        display: inline;
    }
</style>
<script src="https://maps.googleapis.com/maps/api/js?v={{ google_map_version }}&sensor=false"></script>

<script>
(function($) {
    $(document).ready(function() {
        var map_dom_element = $("#map_canvas_{{ id }}")[0];
        var center = new google.maps.LatLng({{ base_lat }}, {{ base_lng }});
        var base_lnglat = {{ base_lng }} + "," + {{ base_lat }};
        console.log(base_lnglat);
        $("#{{ id }}").val(base_lnglat);
        var options = {
            zoom: 15,
            center: center
        };
        var map = new google.maps.Map(map_dom_element, options);
        var marker = new google.maps.Marker({
            map: map,
            position: center
        });
        google.maps.event.addListener(map, "click", function(e) {
            marker.setPosition(e.latLng);
            var lnglat = e.latLng.lng() + "," + e.latLng.lat();
            console.log(lnglat);
            $("#{{ id }}").val(lnglat);
        });
    });
})(jQuery);
</script>

<div id="map_canvas_{{ id }}" style="width: {{ width }}; height: {{ height }};">map loading ...</div>

blog/templates/blog/post_confirm_delete.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="alert alert-danger">
        Are you sure to delete this post?
    </div>

    <form action="" method="post">
        {% csrf_token %}
        {% buttons %}
            <button type="submit" class="btn btn-danger">Yes</button>
        {% endbuttons %}
    </form>

    <hr/>

    <a href="{% url "blog:index" %}" class="btn btn-default">List</a>
{% endblock %}

blog/templates/blog/post_delete_confirm.html
{% extends "layout.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class="alert alert-danger">
        Are you sure to delete this post?
    </div>

    <form action="" method="post">
        {% csrf_token %}
        {% buttons %}
            <button type="submit" class="btn btn-danger">Yes</button>
        {% endbuttons %}
    </form>

    <hr/>

    <a href="{% url "blog:index" %}" class="btn btn-default">List</a>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "layout.html" %}
{% load bootstrap3 blog_tags staticfiles %}

{% block extra_script %}
<link rel="stylesheet" href="{% static "blog/post_detail.css" %}" />
<script src="{% static "blog/post_detail.js" %}"></script>
{% endblock %}

{% block navbar_brand %}
    <a class="navbar-brand" href="{% url "blog:author_home" author.username %}">{{ author }}'s blog</a>
{% endblock %}

{% block content %}
    <p class="text-right">
        <a href="{% url "blog:post_edit" post.id %}" class="btn btn-info">Edit</a>
        <a href="{% url "blog:post_delete" post.id %}" class="btn btn-danger">Delete</a>
        <a href="{% url "blog:author_home" post.author %}" class="btn btn-default">List</a>
    </p>
    <div class="panel panel-default">
        <div class="panel-heading">
            {{ post.title }}
        </div>
        <div class="panel-body">
            <p class="post_attached_image">
                {% if post.attached_image %}
                    <img src="{{ post.attached_image.url }}" />
                {% endif %}
            </p>
            {% if post.lnglat %}
                <img class="post_thumbnail_map" src="http://maps.googleapis.com/maps/api/staticmap?center={{ post.lat }},{{ post.lng }}&zoom=11&size=150x150&markers=color:red%7Clabel:A%7C{{ post.lat }},{{ post.lng }}" />
            {% endif %}
            {{ post.content|linebreaks }}
        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col-sm-6">
                    <span>{{ post.liked_users.all.count }} people liked.</span>
                    {% if user.is_authenticated %}
                        {% if post|is_liked_post:user %}
                            <a href="{% url "blog:post_unlike" post.id %}">Unlike</a>
                        {% else %}
                            <a href="{% url "blog:post_like" post.id %}">Like</a>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="col-sm-6 text-right">
                    <span>by {{ post.author }}, Updated at : {{ post.updated_at }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="panel panel-default">
        <div class="panel-heading">Comments</div>
        <div class="panel-body">
            <form id="comment_form" action="{% url 'blog:comment_new' post.id %}" method="post">
                {% csrf_token %}
                {% bootstrap_form comment_form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary btn-block">Post</button>
                {% endbuttons %}
            </form>
            <table id="comment_list" class="table table-hover">
            <tbody>
            {% for comment in post.comment_set.all %}
            <tr>
                <td>
                    <pre>{{ comment.message }}</pre>
                    <span>{{ comment.updated_at }}</span>
                    <a href="{% url "blog:comment_edit" post.id comment.id %}">Edit</a>
                    <a href="{% url "blog:comment_delete" post.id comment.id %}" class="text-danger comment-delete-confirm">Delete</a>
                </td>
            </tr>
            {% endfor %}
            </tbody>
            </table>
        </div>
    </div>
{% endblock %}

blog/templates/blog/post_form.html
{% include "blog/form.html" %}

blog/templates/blog/post_list.html
{% extends "layout.html" %}
{% load blog_tags %}
{% block navbar_brand %}
    <a class="navbar-brand" href="{% url "blog:author_home" author.username %}">{{ author }}'s blog</a>
{% endblock %}
{% block navbar %}
    {% if not user|is_following:author %}
        <li><a href="{% url "blog:author_follow" author.username %}">Follow</a></li>
    {% else %}
        <li><a href="{% url "blog:author_unfollow" author.username %}">Unfollow</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <span>Followers</span>
    <ul>
        {% for follow in author.follower_set.all %}
            <li>{{ follow.from_user }}</li>
        {% empty %}
            <li>Empty</li>
        {% endfor %}
    </ul>
<table class="table table-hover table-bordered">
    {% for post in post_list %}
    <tr>
        <td>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </td>
        <td>{{ post.updated_at }}</td>
    </tr>
    {% empty %}
    <tr>
        <td colspan="2">No post.</td>
    </tr>
    {% endfor %}
</table>

<hr/>
<a href="{% url "blog:post_new" %}" class="btn btn-default">New Post</a>
{% endblock %}